In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Libraries imported successfully!")

Libraries imported successfully!

In [4]:
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

print("Movies dataset shape:", movies.shape)
print("Credits dataset shape:", credits.shape)

Movies dataset shape: (4803, 20)
Credits dataset shape: (4803, 4)

In [5]:
print("Movies columns:")
print(movies.columns.tolist())

print("\nCredits columns:")
print(credits.columns.tolist())

Movies columns:
['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language', 'original_title', 'overview', 'popularity', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title', 'vote_average', 'vote_count']

Credits columns:
['movie_id', 'title', 'cast', 'crew']

In [6]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [7]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
movies = movies.merge(credits, on="title")

print("Merged dataset shape:", movies.shape)

Merged dataset shape: (4809, 23)

In [9]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
movies = movies[
    [
        "movie_id",
        "title",
        "overview",
        "genres",
        "keywords",
        "cast",
        "crew"
    ]
]

movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [11]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [12]:
movies.duplicated().sum()

np.int64(0)

In [13]:
print(movies.isnull().sum())
print("\nDuplicates:", movies.duplicated().sum())

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

Duplicates: 0

In [14]:
movies.dropna(inplace=True)
movies.drop_duplicates(inplace=True)

print("Dataset shape after cleaning:", movies.shape)

Dataset shape after cleaning: (4806, 7)

In [15]:
import ast

In [16]:
def convert(text):
    names = []
    
    for item in ast.literal_eval(text):
        names.append(item["name"])
        
    return names

In [17]:
movies["genres"] = movies["genres"].apply(convert)
movies["keywords"] = movies["keywords"].apply(convert)

In [18]:
movies[["title", "genres", "keywords"]].head()

,title,genres,keywords
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon..."
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ..."
2,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi..."
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i..."
4,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel..."

In [19]:
def convert_cast(text):
    names = []
    counter = 0
    
    for item in ast.literal_eval(text):
        if counter < 3:
            names.append(item["name"])
            counter += 1
        else:
            break
            
    return names

In [20]:
movies["cast"] = movies["cast"].apply(convert_cast)

In [21]:
movies[["title", "cast"]].head()

,title,cast
0,Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]"
1,Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley]"
2,Spectre,"[Daniel Craig, Christoph Waltz, Léa Seydoux]"
3,The Dark Knight Rises,"[Christian Bale, Michael Caine, Gary Oldman]"
4,John Carter,"[Taylor Kitsch, Lynn Collins, Samantha Morton]"

In [22]:
def fetch_director(text):
    directors = []
    
    for item in ast.literal_eval(text):
        if item["job"] == "Director":
            directors.append(item["name"])
            break
            
    return directors

In [23]:
movies["crew"] = movies["crew"].apply(fetch_director)

In [24]:
movies[["title", "crew"]].head()

                                      title                 crew
0                                    Avatar      [James Cameron]
1  Pirates of the Caribbean: At World's End     [Gore Verbinski]
2                                   Spectre         [Sam Mendes]
3                     The Dark Knight Rises  [Christopher Nolan]
4                               John Carter     [Andrew Stanton]

In [25]:
movies["overview"] = movies["overview"].apply(lambda x: x.split())

In [26]:
movies["overview"].head()

0    [In, the, 22nd, century,, a, paraplegic, Marin...
1    [Captain, Barbossa,, long, believed, to, be, d...
2    [A, cryptic, message, from, Bond’s, past, send...
3    [Following, the, death, of, District, Attorney...
4    [John, Carter, is, a, war-weary,, former, mili...
Name: overview, dtype: object

In [27]:
movies["genres"] = movies["genres"].apply(
    lambda x: [i.replace(" ", "") for i in x]
)

movies["keywords"] = movies["keywords"].apply(
    lambda x: [i.replace(" ", "") for i in x]
)

movies["cast"] = movies["cast"].apply(
    lambda x: [i.replace(" ", "") for i in x]
)

movies["crew"] = movies["crew"].apply(
    lambda x: [i.replace(" ", "") for i in x]
)

In [28]:
movies[["title", "genres", "cast", "crew"]].head()

,title,genres,cast,crew
0,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,Spectre,"[Action, Adventure, Crime]","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,John Carter,"[Action, Adventure, ScienceFiction]","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [29]:
movies["tags"] = (
    movies["overview"]
    + movies["genres"]
    + movies["keywords"]
    + movies["cast"]
    + movies["crew"]
)

In [30]:
new_df = movies[["movie_id", "title", "tags"]].copy()

In [31]:
new_df["tags"] = new_df["tags"].apply(lambda x: " ".join(x))

In [32]:
new_df["tags"] = new_df["tags"].apply(lambda x: x.lower())

In [33]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [35]:
tfidf = TfidfVectorizer(
    max_features=5000,
    stop_words="english"
)

In [36]:
vectors = tfidf.fit_transform(new_df["tags"])

In [37]:
print("TF-IDF matrix shape:", vectors.shape)

TF-IDF matrix shape: (4806, 5000)

In [38]:
from sklearn.metrics.pairwise import cosine_similarity

In [39]:
similarity = cosine_similarity(vectors)

In [40]:
print("Similarity matrix shape:", similarity.shape)

Similarity matrix shape: (4806, 4806)

In [46]:
def recommend(movie, n=5):
    matches = new_df[
        new_df["title"].str.lower() == movie.lower()
    ]

    if matches.empty:
        print("Movie not found in the dataset.")
        return

    movie_index = matches.index[0]
    position = new_df.index.get_loc(movie_index)

    distances = similarity[position]

    movie_list = sorted(
        enumerate(distances),
        key=lambda x: x[1],
        reverse=True
    )[1:n+1]

    print(f"Top {n} movies similar to '{movie}':\n")

    for rank, (index, score) in enumerate(movie_list, start=1):
        title = new_df.iloc[index]["title"]

        print(
            f"{rank}. {title} "
            f"(Similarity: {score:.2%})"
        )

In [47]:
recommend("Interstellar")

Top 5 movies similar to 'Interstellar':

1. Apollo 13 (Similarity: 20.71%)
2. Space Pirate Captain Harlock (Similarity: 20.02%)
3. Space Cowboys (Similarity: 19.34%)
4. The Martian (Similarity: 18.89%)
5. Moonraker (Similarity: 17.79%)

In [48]:
recommend("The Dark Knight")

Top 5 movies similar to 'The Dark Knight':

1. The Dark Knight Rises (Similarity: 45.60%)
2. Batman Returns (Similarity: 38.30%)
3. Batman Begins (Similarity: 36.64%)
4. Batman Forever (Similarity: 30.32%)
5. Batman: The Dark Knight Returns, Part 2 (Similarity: 29.17%)

In [49]:
recommend("Avatar")

Top 5 movies similar to 'Avatar':

1. Aliens (Similarity: 19.52%)
2. Falcon Rising (Similarity: 19.45%)
3. Battle: Los Angeles (Similarity: 18.54%)
4. Apollo 18 (Similarity: 17.56%)
5. Star Trek Into Darkness (Similarity: 16.34%)

In [50]:
recommend("Interstellar")

Top 5 movies similar to 'Interstellar':

1. Apollo 13 (Similarity: 20.71%)
2. Space Pirate Captain Harlock (Similarity: 20.02%)
3. Space Cowboys (Similarity: 19.34%)
4. The Martian (Similarity: 18.89%)
5. Moonraker (Similarity: 17.79%)

In [51]:
recommend("The Dark Knight", 10)

Top 10 movies similar to 'The Dark Knight':

1. The Dark Knight Rises (Similarity: 45.60%)
2. Batman Returns (Similarity: 38.30%)
3. Batman Begins (Similarity: 36.64%)
4. Batman Forever (Similarity: 30.32%)
5. Batman: The Dark Knight Returns, Part 2 (Similarity: 29.17%)
6. Batman v Superman: Dawn of Justice (Similarity: 25.39%)
7. Batman & Robin (Similarity: 23.09%)
8. Batman (Similarity: 22.79%)
9. Batman (Similarity: 20.75%)
10. The Lego Movie (Similarity: 14.24%)

In [52]:
import nltk
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

print("Stemmer ready!")

Stemmer ready!

In [53]:
def stem(text):
    words = []

    for word in text.split():
        words.append(ps.stem(word))

    return " ".join(words)

In [54]:
print(stem("connect connected connecting connection"))

connect connect connect connect

In [55]:
new_df["stemmed_tags"] = new_df["tags"].apply(stem)

In [56]:
new_df[["title", "tags", "stemmed_tags"]].head()

,title,tags,stemmed_tags
0,Avatar,"in the 22nd century, a paraplegic marine is di...","in the 22nd century, a parapleg marin is dispa..."
1,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha...","captain barbossa, long believ to be dead, ha c..."
2,Spectre,a cryptic message from bond’s past sends him o...,a cryptic messag from bond’ past send him on a...
3,The Dark Knight Rises,following the death of district attorney harve...,follow the death of district attorney harvey d...
4,John Carter,"john carter is a war-weary, former military ca...","john carter is a war-weary, former militari ca..."

In [57]:
tfidf_stemmed = TfidfVectorizer(
    max_features=5000,
    stop_words="english"
)

vectors_stemmed = tfidf_stemmed.fit_transform(
    new_df["stemmed_tags"]
)

print("Stemmed TF-IDF shape:", vectors_stemmed.shape)

Stemmed TF-IDF shape: (4806, 5000)

In [58]:
similarity_stemmed = cosine_similarity(vectors_stemmed)

print(
    "Stemmed similarity matrix shape:",
    similarity_stemmed.shape
)

Stemmed similarity matrix shape: (4806, 4806)

In [59]:
def recommend_stemmed(movie, n=5):
    matches = new_df[
        new_df["title"].str.lower() == movie.lower()
    ]

    if matches.empty:
        print("Movie not found in the dataset.")
        return

    movie_index = matches.index[0]
    position = new_df.index.get_loc(movie_index)

    distances = similarity_stemmed[position]

    movie_list = sorted(
        enumerate(distances),
        key=lambda x: x[1],
        reverse=True
    )[1:n+1]

    print(f"Top {n} movies similar to '{movie}' using stemming:\n")

    for rank, (index, score) in enumerate(movie_list, start=1):
        title = new_df.iloc[index]["title"]

        print(
            f"{rank}. {title} "
            f"(Similarity: {score:.2%})"
        )

In [60]:
recommend_stemmed("Interstellar")

Top 5 movies similar to 'Interstellar' using stemming:

1. Apollo 13 (Similarity: 21.79%)
2. The Right Stuff (Similarity: 20.46%)
3. The Martian (Similarity: 19.77%)
4. Space Pirate Captain Harlock (Similarity: 19.77%)
5. Space Cowboys (Similarity: 19.08%)

In [61]:
recommend_stemmed("The Dark Knight")

Top 5 movies similar to 'The Dark Knight' using stemming:

1. The Dark Knight Rises (Similarity: 46.02%)
2. Batman Returns (Similarity: 39.59%)
3. Batman Begins (Similarity: 36.31%)
4. Batman Forever (Similarity: 29.92%)
5. Batman: The Dark Knight Returns, Part 2 (Similarity: 28.64%)

In [62]:
import pickle

pickle.dump(
    new_df,
    open("movies.pkl", "wb")
)

pickle.dump(
    similarity_stemmed,
    open("similarity.pkl", "wb")
)

print("Files saved successfully!")

Files saved successfully!

In [63]:
print(type(vectors_stemmed))
print(vectors_stemmed.shape)

<class 'scipy.sparse._csr.csr_matrix'>
(4806, 5000)

In [64]:
import pickle

pickle.dump(
    vectors_stemmed,
    open("tfidf_matrix.pkl", "wb")
)

print("TF-IDF matrix saved!")

TF-IDF matrix saved!